spring:
  application.name: flyway
  datasource:
    url: jdbc:mysql://localhost:3306/river?serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true
    out-of-order: false
    baseline-version: 202502281454
