spring.application.name: spring-security-jwt


jwt:
  secret-key: 8t8Ob7d0zcU7qlTQ98jIf1Zc3xiZO2W259EIqYLvM2s=
  token:
    access-seconds: 3600        # 1시간 (3600초)
    refresh-seconds: 2592000    # 30일 (30 * 24 * 60 * 60초)